### ISSUE TITLE
如何改格式？

### ISSUE THREAD

**Issue by chiyi4488** [justjavac/github-actions-youtube-dl#3]
你好，想請教要如何修改下載影片的格式，我實在找不到參數位置......

**Comment by justjavac** [comment]
https://github.com/justjavac/github-actions-youtube-dl/blob/main/.github/workflows/ci.yml#L18

第 18 行

**Comment by chiyi4488** [comment]
直接在這裡加是嗎？(不是在config?!

**Comment by justjavac** [comment]
应该都行吧，去看看 youtube-dl 的文档吧，应该比较详细
